<?php

namespace App\Services;

use Core\Database;

class ColumnService
{
    private static array $defaultLabels = [
        'contacts' => [
            'account_code' => 'Mã KH',
            'tax_code' => 'Mã số thuế',
            'full_name' => 'Họ và tên',
            'company_name' => 'Tên công ty',
            'company_phone' => 'Điện thoại công ty',
            'company_email' => 'Email công ty',
            'industry' => 'Ngành KD',
            'company_size' => 'Quy mô',
            'title' => 'Danh xưng',
            'email' => 'Email',
            'website' => 'Website',
            'phone' => 'Điện thoại',
            'mobile' => 'Di động',
            'fax' => 'Fax',
            'position' => 'Chức vụ',
            'company_id' => 'Công ty',
            'source_id' => 'Nguồn KH',
            'relation_id' => 'Mối quan hệ (ID)',
            'industry_id' => 'Ngành KD (ID)',
            'address' => 'Địa chỉ',
            'city' => 'Thành phố',
            'country' => 'Quốc gia',
            'province' => 'Tỉnh/TP',
            'district' => 'Quận/Huyện',
            'ward' => 'Phường/Xã',
            'latitude' => 'Kinh độ',
            'longitude' => 'Vĩ độ',
            'referrer_type' => 'Loại giới thiệu',
            'referrer_code' => 'Người giới thiệu',
            'date_of_birth' => 'Ngày sinh',
            'gender' => 'Giới tính',
            'description' => 'Mô tả',
            'avatar' => 'Ảnh đại diện',
            'status' => 'Mối quan hệ',
            'customer_group' => 'Nhóm KH',
            'total_revenue' => 'Tổng doanh thu',
            'owner_id' => 'Phụ trách',
            'created_by' => 'Người tạo',
            'last_activity_at' => 'LH lần cuối',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Ngày cập nhật',
            'portal_token' => 'Token portal',
            'portal_active' => 'Portal KH',
        ],
        'orders' => [
            'order_number' => 'Mã ĐH',
            'type' => 'Loại',
            'status' => 'Trạng thái',
            'contact_id' => 'Khách hàng',
            'company_id' => 'Công ty',
            'deal_id' => 'Cơ hội',
            'contract_id' => 'Hợp đồng',
            'order_source_id' => 'Nguồn ĐH',
            'campaign_id' => 'Chiến dịch',
            'subtotal' => 'Tạm tính',
            'tax_amount' => 'Thuế',
            'discount_amount' => 'Chiết khấu',
            'discount_type' => 'Loại CK',
            'transport_amount' => 'Phí vận chuyển',
            'installation_amount' => 'Phí lắp đặt',
            'total' => 'Tổng tiền',
            'currency' => 'Tiền tệ',
            'notes' => 'Ghi chú',
            'order_terms' => 'Điều khoản',
            'payment_status' => 'Thanh toán',
            'payment_method' => 'Hình thức TT',
            'lading_code' => 'Mã vận đơn',
            'shipping_address' => 'ĐC giao hàng',
            'shipping_contact' => 'Người nhận',
            'shipping_phone' => 'SĐT nhận',
            'shipping_province' => 'Tỉnh/TP giao',
            'shipping_district' => 'Q/H giao',
            'lading_status' => 'TT vận đơn',
            'warehouse_id' => 'Kho',
            'tracking_url' => 'Link tracking',
            'paid_amount' => 'Đã thanh toán',
            'payment_date' => 'Ngày thanh toán',
            'commission_amount' => 'Hoa hồng',
            'due_date' => 'Hạn thanh toán',
            'issued_date' => 'Ngày phát hành',
            'owner_id' => 'Phụ trách',
            'created_by' => 'Người tạo',
            'approved_by' => 'Người duyệt',
            'approved_at' => 'Ngày duyệt',
            'cancelled_at' => 'Ngày hủy',
            'cancelled_reason' => 'Lý do hủy',
            'is_auto_approve' => 'Tự duyệt',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Ngày cập nhật',
        ],
        'contracts' => [
            'contract_number' => 'Số HĐ',
            'contract_code' => 'Mã HĐ',
            'title' => 'Tên hợp đồng',
            'type' => 'Kiểu HĐ',
            'payment_method' => 'Hình thức TT',
            'usage_type' => 'HĐ sử dụng',
            'status' => 'Trạng thái',
            'value' => 'Giá trị HĐ',
            'subtotal' => 'Tổng tiền hàng',
            'discount_amount' => 'Chiết khấu',
            'discount_percent' => 'CK (%)',
            'shipping_fee' => 'Phí vận chuyển',
            'shipping_fee_percent' => 'Phí VC (%)',
            'installation_fee' => 'Phí lắp đặt',
            'installation_fee_percent' => 'Phí LĐ (%)',
            'tax_amount' => 'Tổng thuế',
            'actual_value' => 'Giá trị thực',
            'executed_amount' => 'Đã thực hiện',
            'paid_amount' => 'Đã thanh toán',
            'installation_address' => 'ĐC lắp đặt',
            'location' => 'Địa điểm',
            'project' => 'Dự án',
            'recurring_value' => 'GT định kỳ',
            'recurring_cycle' => 'Chu kỳ',
            'contact_id' => 'Khách hàng',
            'company_id' => 'Công ty',
            'party_a_company_id' => 'Công ty bên bán',
            'contact_name' => 'Người liên hệ',
            'deal_id' => 'Cơ hội',
            'quote_id' => 'Báo giá',
            'owner_id' => 'Phụ trách',
            'start_date' => 'Ngày hiệu lực',
            'end_date' => 'Ngày hết hạn',
            'created_date' => 'Ngày tạo HĐ',
            'actual_start_date' => 'TG thực tế BĐ',
            'actual_end_date' => 'TG thực tế KT',
            'signed_date' => 'Ngày ký',
            'auto_renew' => 'Tự gia hạn',
            'parent_contract_id' => 'HĐ gốc',
            'related_contract_id' => 'HĐ liên quan',
            'notes' => 'Ghi chú',
            'terms' => 'Điều khoản',
            'created_by' => 'Người tạo',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Ngày cập nhật',
            'party_a_name' => 'Tên bên bán',
            'party_a_address' => 'ĐC bên bán',
            'party_a_phone' => 'ĐT bên bán',
            'party_a_fax' => 'Fax bên bán',
            'party_a_representative' => 'Đại diện bên bán',
            'party_a_position' => 'CV bên bán',
            'party_a_bank_account' => 'TK bên bán',
            'party_a_bank_name' => 'NH bên bán',
            'party_a_tax_code' => 'MST bên bán',
            'party_b_name' => 'Tên bên mua',
            'party_b_address' => 'ĐC bên mua',
            'party_b_phone' => 'ĐT bên mua',
            'party_b_fax' => 'Fax bên mua',
            'party_b_representative' => 'Đại diện bên mua',
            'party_b_position' => 'CV bên mua',
            'party_b_bank_account' => 'TK bên mua',
            'party_b_bank_name' => 'NH bên mua',
            'party_b_tax_code' => 'MST bên mua',
            'discount_after_tax' => 'CK sau thuế',
            'shipping_after_tax' => 'VC sau thuế',
            'apply_vat' => 'Áp dụng VAT',
            'vat_percent' => 'VAT (%)',
            'vat_amount' => 'Thuế VAT',
            'auto_create_order' => 'Tự tạo ĐH',
            'auto_notify_expiry' => 'Tự báo hết hạn',
            'auto_send_sms' => 'Tự gửi SMS',
            'auto_send_email' => 'Tự gửi email',
        ],
        'quotations' => [
            'quote_number' => 'Mã BG',
            'contact_id' => 'Khách hàng',
            'company_id' => 'Công ty',
            'deal_id' => 'Cơ hội',
            'status' => 'Trạng thái',
            'subtotal' => 'Tạm tính',
            'tax_rate' => 'Thuế VAT (%)',
            'tax_amount' => 'Tiền thuế',
            'discount_percent' => 'Chiết khấu (%)',
            'discount_amount' => 'Chiết khấu',
            'discount_after_tax' => 'CK sau thuế',
            'shipping_percent' => 'Phí VC (%)',
            'shipping_fee' => 'Phí vận chuyển',
            'shipping_after_tax' => 'VC sau thuế',
            'shipping_note' => 'Ghi chú VC',
            'installation_percent' => 'Phí LĐ (%)',
            'installation_fee' => 'Phí lắp đặt',
            'total' => 'Tổng tiền',
            'valid_until' => 'Hiệu lực đến',
            'notes' => 'Ghi chú',
            'terms' => 'Điều khoản',
            'client_note' => 'Ghi chú KH',
            'view_count' => 'Lượt xem',
            'last_viewed_at' => 'Xem lần cuối',
            'accepted_at' => 'Ngày chấp nhận',
            'rejected_at' => 'Ngày từ chối',
            'rejection_reason' => 'Lý do từ chối',
            'owner_id' => 'Phụ trách',
            'created_by' => 'Người tạo',
            'created_at' => 'Ngày tạo',
        ],
        'deals' => [
            'deal_code' => 'Mã CH',
            'title' => 'Tên cơ hội',
            'value' => 'Giá trị',
            'stage_id' => 'Giai đoạn',
            'contact_id' => 'Khách hàng',
            'company_id' => 'Công ty',
            'campaign_id' => 'Chiến dịch',
            'opportunity_status_id' => 'TT cơ hội',
            'status' => 'Trạng thái',
            'priority' => 'Ưu tiên',
            'probability' => 'Xác suất',
            'expected_close_date' => 'Dự kiến đóng',
            'actual_close_date' => 'Ngày đóng TT',
            'receipt_date' => 'Ngày nhận',
            'lost_reason' => 'Lý do mất',
            'loss_reason_category' => 'Nhóm lý do mất',
            'close_reason' => 'Lý do đóng',
            'competitor' => 'Đối thủ',
            'description' => 'Mô tả',
            'owner_id' => 'Phụ trách',
            'created_by' => 'Người tạo',
            'created_at' => 'Ngày tạo',
        ],
        'tasks' => [
            'task_code' => 'Mã CV',
            'title' => 'Công việc',
            'status' => 'Trạng thái',
            'priority' => 'Ưu tiên',
            'progress' => 'Tiến độ',
            'estimated_hours' => 'Giờ dự kiến',
            'color' => 'Màu',
            'is_important' => 'Quan trọng',
            'start_date' => 'Ngày bắt đầu',
            'due_date' => 'Hạn',
            'completed_at' => 'Ngày hoàn thành',
            'cancelled_at' => 'Ngày hủy',
            'assigned_to' => 'Phụ trách',
            'contact_id' => 'Khách hàng',
            'company_id' => 'Công ty',
            'deal_id' => 'Cơ hội',
            'project_id' => 'Dự án',
            'parent_id' => 'CV cha',
            'task_type_id' => 'Loại CV',
            'description' => 'Mô tả',
            'created_by' => 'Người tạo',
            'created_at' => 'Ngày tạo',
        ],
        'products' => [
            'name' => 'Sản phẩm',
            'sku' => 'SKU',
            'barcode' => 'Mã vạch',
            'type' => 'Loại',
            'category_id' => 'Danh mục',
            'origin_id' => 'Xuất xứ',
            'manufacturer_id' => 'Nhà sản xuất',
            'unit' => 'Đơn vị',
            'price' => 'Đơn giá',
            'price_wholesale' => 'Giá sỉ',
            'price_online' => 'Giá online',
            'saleoff_price' => 'Giá KM',
            'discount_percent' => 'CK (%)',
            'cost_price' => 'Giá vốn',
            'tax_rate' => 'Thuế (%)',
            'weight' => 'Trọng lượng',
            'stock_quantity' => 'Tồn kho',
            'min_stock' => 'Tồn tối thiểu',
            'description' => 'Mô tả',
            'short_description' => 'Mô tả ngắn',
            'is_active' => 'Trạng thái',
            'created_by' => 'Người tạo',
            'created_at' => 'Ngày tạo',
        ],
        'companies' => [
            'name' => 'Tên DN',
            'email' => 'Email',
            'phone' => 'Điện thoại',
            'fax' => 'Fax',
            'website' => 'Website',
            'tax_code' => 'MST',
            'industry' => 'Ngành nghề',
            'company_size' => 'Quy mô',
            'address' => 'Địa chỉ',
            'city' => 'Thành phố',
            'province' => 'Tỉnh/TP',
            'district' => 'Quận/Huyện',
            'country' => 'Quốc gia',
            'description' => 'Mô tả',
            'owner_id' => 'Phụ trách',
            'created_by' => 'Người tạo',
            'created_at' => 'Ngày tạo',
        ],
        'order_items' => [
            'order_id' => 'Đơn hàng',
            'product_id' => 'Sản phẩm (ID)',
            'product_name' => 'Tên SP',
            'description' => 'Mô tả',
            'quantity' => 'Số lượng',
            'unit' => 'Đơn vị',
            'unit_price' => 'Đơn giá',
            'cost_price' => 'Giá vốn',
            'tax_rate' => 'Thuế (%)',
            'tax_amount' => 'Tiền thuế',
            'discount_percent' => 'CK (%)',
            'discount' => 'Chiết khấu',
            'total' => 'Thành tiền',
            'note' => 'Ghi chú',
            'sort_order' => 'Thứ tự',
        ],
        'users' => [
            'name' => 'Họ tên',
            'email' => 'Email',
            'phone' => 'Điện thoại',
            'address' => 'Địa chỉ',
            'date_of_birth' => 'Ngày sinh',
            'gender' => 'Giới tính',
            'id_number' => 'Số CMND/CCCD',
            'id_issued_date' => 'Ngày cấp',
            'id_issued_place' => 'Nơi cấp',
            'bank_name' => 'Ngân hàng',
            'bank_account' => 'Số TK',
            'bank_branch' => 'Chi nhánh NH',
            'join_date' => 'Ngày vào',
            'emergency_contact' => 'LH khẩn cấp',
            'emergency_phone' => 'SĐT khẩn cấp',
            'avatar' => 'Ảnh đại diện',
            'role' => 'Vai trò',
            'position_id' => 'Chức vụ',
            'department_id' => 'Phòng ban',
            'is_active' => 'Kích hoạt',
            'last_login' => 'Đăng nhập cuối',
            'base_salary' => 'Lương cơ bản',
            'leave_balance' => 'Phép còn lại',
            'allowance_lunch' => 'PC ăn trưa',
            'allowance_transport' => 'PC đi lại',
            'allowance_phone' => 'PC điện thoại',
            'allowance_other' => 'PC khác',
            'dependents' => 'Người phụ thuộc',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Ngày cập nhật',
        ],
        'tickets' => [
            'ticket_code' => 'Mã ticket',
            'title' => 'Tiêu đề',
            'content' => 'Nội dung',
            'category_id' => 'Danh mục',
            'contact_id' => 'Khách hàng',
            'company_id' => 'Công ty',
            'contact_phone' => 'SĐT liên hệ',
            'contact_email' => 'Email liên hệ',
            'priority' => 'Ưu tiên',
            'status' => 'Trạng thái',
            'status_id' => 'TT chi tiết',
            'assigned_to' => 'Phụ trách',
            'due_date' => 'Hạn',
            'expected_at' => 'Dự kiến xử lý',
            'resolved_at' => 'Ngày giải quyết',
            'closed_at' => 'Ngày đóng',
            'first_response_at' => 'Phản hồi đầu',
            'sla_breached' => 'Vi phạm SLA',
            'created_by' => 'Người tạo',
            'created_at' => 'Ngày tạo',
        ],
    ];

    private static array $systemFields = [
        'id', 'tenant_id', 'is_deleted', 'deleted_at', 'updated_at',
        'avatar', 'logo', 'image', 'featured_image', 'currency',
        'portal_token', 'portal_password', 'portal_active',
        'password', 'sort_order',
    ];

    /**
     * Get displayable columns for a module.
     */
    public static function getColumns(string $module): array
    {
        $defaults = self::$defaultLabels[$module] ?? [];

        // Load overrides from DB
        $hiddenFields = [];
        try {
            $overrides = Database::fetchAll(
                "SELECT field_name, label, show_in_list FROM field_label_overrides WHERE tenant_id = ? AND table_name = ?",
                [Database::tenantId(), $module]
            );
            foreach ($overrides as $ov) {
                if (!empty($ov['label']) && $ov['label'] !== $ov['field_name']) {
                    $defaults[$ov['field_name']] = $ov['label'];
                }
                if (isset($ov['show_in_list']) && $ov['show_in_list']) {
                    if (!isset($defaults[$ov['field_name']])) {
                        $defaults[$ov['field_name']] = $ov['label'] ?: ucfirst(str_replace('_', ' ', $ov['field_name']));
                    }
                } elseif (isset($ov['show_in_list']) && !$ov['show_in_list']) {
                    $hiddenFields[$ov['field_name']] = true;
                }
            }
        } catch (\Exception $e) {}

        // Load custom fields
        try {
            $customFields = Database::fetchAll(
                "SELECT field_name, field_label FROM custom_fields WHERE module = ? AND tenant_id = ?",
                [$module, Database::tenantId()]
            );
            foreach ($customFields as $cf) {
                $defaults['cf_' . $cf['field_name']] = $cf['field_label'];
            }
        } catch (\Exception $e) {}

        $columns = [];
        foreach ($defaults as $field => $label) {
            if (isset($hiddenFields[$field])) continue;
            $columns[] = [
                'key' => 'col-' . str_replace('_', '', $field),
                'field' => $field,
                'label' => $label,
                'is_system' => in_array($field, self::$systemFields),
            ];
        }

        return $columns;
    }
}
